name: 3d-reconstruction-app
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit
    - torch
    - transformers
    - pillow
    - numpy
    - open3d==0.18.0
    - matplotlib
    - plotly